name: ci

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest


    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    steps:
      - name: repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.0

      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: build
        run: yarn build

      - name: Run Linter and prettier
        run: yarn lint

      - name: Run Jest Tests
        run: yarn test

